services:
  auth-service:
    container_name: auth-service
    image: auth-service:release
    network_mode: host
    env_file:
      - ../.env
    build: ..
    volumes:
      - /home/mgreif/logs/auth-service:/app/logs
